Repository nestdotland/nest.land, pull requests merged in 2020-10, with the labels that each got.

#278 Relative URL replacement refactor
  src/views/PackageDetail.vue
Labels: hacktoberfest-accepted

#279 gallery: show total modules
  api/all-packages.js
  src/views/Gallery.vue
Labels: hacktoberfest-accepted

#281 Update linter
  .github/linters/.eslintrc.yml
  .github/workflows/linter.yml
  src/views/PackageDetail.vue
Labels: hacktoberfest-accepted

#282 [BREAKING CHANGE] Remove eggs version helper
  eggs/src/README.md
  eggs/src/version.ts
Labels: component: eggs, hacktoberfest-accepted

#286 Server side README API
  api/readme.ts
  package.json
  src/views/PackageDetail.vue
  yarn.lock
Labels: hacktoberfest-accepted

#285 No README message
  src/views/PackageDetail.vue
Labels: aspect: modules, hacktoberfest-accepted

#288 Git hooks
  .github/commits-style.md
  package.json
  src/views/PackageDetail.vue
  verify_commit.js
Labels: hacktoberfest-accepted

#291 fix(readme api): Don't replace hash links
  api/readme.ts
Labels: hacktoberfest-accepted

#290 New dependency viewer
  public/index.html
  src/components/Tree/NodeTree.vue
  src/components/Tree/Tree.vue
  src/components/Tree/UrlRegistry.vue
  src/main.js
  src/modules/hatcher/registries.js
  src/modules/hatcher/registries/DenoLand.js
  src/modules/hatcher/registries/Denopkg.js
  src/modules/hatcher/registries/Github.js
  src/modules/hatcher/registries/NestLand.js
  src/modules/hatcher/utilities/utils.js
  src/modules/import-tree/importTree.js
  src/views/PackageDetail.vue
  src/views/StdGallery.vue
Labels: hacktoberfest-accepted, type: feature
