Repository nestdotland/nest.land, pull requests merged in 2020-07, with the labels that each got.

#196 Change org name from nestlandofficial ➜ nestdotland
  README.md
  eggs/README.md
  eggs/egg.json
  web/src/assets/docs/DOCUMENTATION.md
Labels: documentation

#199 [FIX] Updated username and footer credits
  README.md
  web/src/components/Footer.vue
Labels: documentation

#210 Move readme to .github dir.
  .github/README.md
Labels: meta: documentation, priority: low, semver: patch, type: chore

#220 [CHORE] Update correct email in the code of conduct
  .github/CODE_OF_CONDUCT.md
Labels: type: chore

#224 [FEAT] std
  src/components/Card.vue
  src/components/Nav.vue
  src/components/home/FAQ.vue
  src/components/package/FileExplorer.vue
  src/main.js
  src/routes.js
  src/styles/Markdown.sass
  src/views/StdGallery.vue
  src/views/StdModule.vue
Labels: aspect: UI/styling, aspect: gallery, priority: high, type: feature
